import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased scroll-smooth bg-black min-h-screen`}
      >
        <div className="relative">
          <div className="fixed inset-0 bg">
            <div className="isolate">
              <div className="noise"></div>
              <div className="overlay"></div>
            </div>
          </div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
